# Bybit API 설정
bybit:
  testnet: true  # 테스트넷 사용 여부
  market_type: "linear"  # linear/inverse
  leverage: 1  # 레버리지 설정

# 트레이딩 설정
trading:
  symbols: ["BTCUSDT", "ETHUSDT"]  # 거래 페어
  timeframes: ["15", "60", "240"]  # Bybit에서 지원하는 interval 값
  risk_per_trade: 0.02  # 거래당 리스크 비율 (2%)
  max_positions: 3  # 최대 동시 포지션 수

# 기술적 지표 설정
indicators:
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
  
# 백테스팅 설정
backtest:
  start_date: "2023-01-01"
  initial_balance: 10000  # USDT

# 로깅 설정
logging:
  level: "INFO"
  save_trades: true 